Update casa6 commit
CARTAvis/carta-casacore pull request #11
Opened 2021-03-16 19:52 UTC by pford

casa6 commit from February 2021 includes:

- CRTF ICRS import conversion fix
- CRTF parser regex fix for Mac OSX
- Dynamic exception fix in stdcasa

Removed `patch_stdcasa_variant` workaround in imageanalysis/CMakeLists.txt, no longer needed due to dynamic exception fix.

2021-03-16 20:12 UTC, confluence requested changes
We should merge these changes from the 18th of August from the casacore CMakeLists.txt into our main CMakeLists.txt (which replaces it). It probably doesn't make any practical difference to us, but I would like these files to stay in sync except for necessary changes:

https://github.com/casacore/casacore/commit/e39ebb3191ae10cc7c10c9b175ef5a8389b5587a#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a

Other than that, this looks straightforward.

2021-03-16 21:47 UTC, confluence approved these changes
OK, looks good to me!

2021-03-17 02:20 UTC, ajm-asiaa requested changes
I think these commits have somehow made things worse on Ubuntu. I now appear to be getting a segmentation fault when opening a 2000+ point CRTF file whereas before it only gave a warning about "Illegal polygon specification” in the console. Unless I am doing something wrong?

@confluence Are you able to open the attached 2000 point CRTF file? (I have zipped it in order to allow it to be hosted on Github, so please unzip it first.)
[polygon_2000.crtf.zip](https://github.com/CARTAvis/carta-casacore/files/6153287/polygon_2000.crtf.zip)

2021-03-17 07:19 UTC, confluence commented
I can confirm this issue at my end (on Ubuntu Focal; both casacore and backend rebuilt in `RelWithDebInfo`).

2022-02-25 16:30 UTC, pford commented
Closing old PR

2022-02-25 16:30 UTC, closed without merging